FROM openjdk:17

WORKDIR /app

# Instala curl e jq
RUN apt-get update && apt-get install -y curl jq

# Define a versão
ENV MC_VERSION=1.20.1

# Baixa o build mais recente e o server.jar
RUN BUILD=$(curl -s https://api.papermc.io/v2/projects/paper/versions/$MC_VERSION | jq -r '.builds[-1]') && \
    JAR_NAME=paper-$MC_VERSION-$BUILD.jar && \
    curl -o server.jar https://api.papermc.io/v2/projects/paper/versions/$MC_VERSION/builds/$BUILD/downloads/$JAR_NAME

# Aceita o EULA
RUN echo "eula=true" > eula.txt

EXPOSE 25565

CMD ["java", "-Xmx1G", "-Xms1G", "-jar", "server.jar", "nogui"]


